// <auto-generated />
using System;
using Acme.SubscriberService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acme.SubscriberService.Migrations;

[DbContext(typeof(DatabaseContext))]
[Migration("20240919195720_InitDatabase")]
partial class InitDatabase
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

        modelBuilder.Entity("Acme.SubscriberService.Models.Subscription", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<DateTime>("ExpirationDate")
                    .HasColumnType("datetime(6)");

                b.HasKey("Id");

                b.ToTable("Subscriptions");
            });
#pragma warning restore 612, 618
    }
}
